"""Research primitives for latent audio memory and composition."""

from .composition import (
    TransitionWeights,
    best_path,
    bridge_cost,
    loop_cost,
    ranked_bridges,
    ranked_continuations,
    transition_cost,
)
from .index import LatentMemoryIndex, SearchResult
from .io import load_item, load_items, save_item, save_items
from .prompt_optimization import (
    GreedyPromptSearchResult,
    PromptOptimizationResult,
    coordinate_prompt_search,
    default_modifier_axes,
    greedy_token_prompt_search,
    prompt_seed_from_audio_path,
)
from .latent_math import (
    as_time_major,
    boundary_summary,
    cosine_similarity,
    euclidean_distance,
    latent_summary,
)
from .schema import LatentItem
from .audio_vectors import (
    AudioSetDirection,
    apply_frame_direction,
    frame_mean_direction,
    load_summary_direction,
    save_audio_frame_direction,
    save_summary_direction,
    summary_direction,
)
from .style import (
    LatentStyleDirection,
    LatentStyleProfile,
    apply_profile_attraction,
    apply_profile_to_item,
    apply_style_direction,
    fit_style_profile,
    load_style_direction,
    load_style_profile,
    save_style_direction,
    save_style_profile,
    style_direction,
)
from .experiments.soft_prompt import SoftPromptState
from .colab_audio_player import audio_player_html, display_audio_player
from .tokenizer_vocab import (
    TokenizerVocabularyConfig,
    extract_prompt_tokenizer,
    native_tokenizer_vocabulary,
    preview_native_tokenizer_vocabulary,
)
from .selective_renoise import (
    LatentMaskSpec,
    SelectiveRenoiseResult,
    channel_mask_like,
    masked_latent_noise,
    sampler_noise_for_channels,
    select_latent_channels,
    selective_renoise_sa3,
)
from .latent_blur import (
    LatentBlurSpec,
    apply_latent_blur,
    channel_blur_latents,
    detail_attenuate_latents,
    low_rank_latents,
    sa3_sample_from_init_latents,
    temporal_box_blur_latents,
    temporal_blur_latents,
)

__all__ = [
    "LatentItem",
    "LatentMemoryIndex",
    "SearchResult",
    "TransitionWeights",
    "TokenizerVocabularyConfig",
    "LatentMaskSpec",
    "LatentBlurSpec",
    "SelectiveRenoiseResult",
    "LatentStyleDirection",
    "LatentStyleProfile",
    "AudioSetDirection",
    "PromptOptimizationResult",
    "GreedyPromptSearchResult",
    "SoftPromptState",
    "apply_frame_direction",
    "apply_latent_blur",
    "apply_profile_attraction",
    "apply_profile_to_item",
    "apply_style_direction",
    "audio_player_html",
    "as_time_major",
    "best_path",
    "boundary_summary",
    "bridge_cost",
    "channel_mask_like",
    "channel_blur_latents",
    "cosine_similarity",
    "coordinate_prompt_search",
    "default_modifier_axes",
    "detail_attenuate_latents",
    "display_audio_player",
    "euclidean_distance",
    "extract_prompt_tokenizer",
    "frame_mean_direction",
    "greedy_token_prompt_search",
    "fit_style_profile",
    "latent_summary",
    "load_item",
    "load_items",
    "load_style_direction",
    "load_style_profile",
    "load_summary_direction",
    "loop_cost",
    "low_rank_latents",
    "masked_latent_noise",
    "native_tokenizer_vocabulary",
    "preview_native_tokenizer_vocabulary",
    "prompt_seed_from_audio_path",
    "ranked_bridges",
    "ranked_continuations",
    "save_item",
    "save_items",
    "save_style_direction",
    "save_style_profile",
    "save_summary_direction",
    "save_audio_frame_direction",
    "sa3_sample_from_init_latents",
    "sampler_noise_for_channels",
    "select_latent_channels",
    "selective_renoise_sa3",
    "style_direction",
    "summary_direction",
    "temporal_box_blur_latents",
    "temporal_blur_latents",
    "transition_cost",
]
