from __future__ import annotations

from .contracts import NotebookMode, OperatorName


COLAB_MODES: tuple[NotebookMode, ...] = (
    NotebookMode(
        mode_id="0",
        title="Renoise variation / local neighborhood sampling",
        priority="P1",
        maturity="lab",
        status="native app surface",
        native_surface="Listening Bench audio-to-audio generation with init_noise_level",
        operators=[OperatorName.AUDIO_TO_AUDIO],
        inputs=["source audio", "init_noise_level", "seed", "steps", "prompt"],
        outputs=["audio artifact", "recipe", "lineage"],
    ),
    NotebookMode(
        mode_id="0c",
        title="Latent-selective renoise playground",
        priority="P1",
        maturity="lab",
        status="native app surface",
        native_surface="Latent Lab operator: latent.renoise",
        operators=[OperatorName.LATENT_RENOISE],
        inputs=["source latent", "mask mode", "fraction", "sigma", "seed"],
        outputs=["latent artifact", "recipe", "selected channel metadata"],
    ),
    NotebookMode(
        mode_id="0c-search",
        title="Search annotated variations",
        priority="P2",
        maturity="lab",
        status="native app surface",
        native_surface="Artifact annotation panel plus archive search by label, notes, and tags",
        operators=[OperatorName.ANNOTATE],
        inputs=["artifact labels", "notes", "tags", "rating metadata"],
        outputs=["updated artifact metadata"],
        notes="The old Colab JSON annotation search should become a first-class artifact filter.",
    ),
    NotebookMode(
        mode_id="0e",
        title="Cross-audio latent channel graft",
        priority="P1",
        maturity="lab",
        status="native app surface",
        native_surface="Latent Lab operator: latent.graft with donor latent",
        operators=[OperatorName.LATENT_GRAFT],
        inputs=["source latent", "donor latent", "mask mode", "fraction", "amount"],
        outputs=["latent artifact", "recipe", "source/donor lineage"],
    ),
    NotebookMode(
        mode_id="0d",
        title="Latent blur playground",
        priority="P1",
        maturity="lab",
        status="native app surface",
        native_surface="Latent Lab operator: latent.blur",
        operators=[OperatorName.LATENT_BLUR],
        inputs=["source latent", "blur/DSP mode", "strength"],
        outputs=["latent artifact", "recipe"],
    ),
    NotebookMode(
        mode_id="0h",
        title="Neural latent DSP playground",
        priority="P1",
        maturity="lab",
        status="native app surface",
        native_surface="Latent Lab operator: latent.dsp",
        operators=[OperatorName.LATENT_DSP],
        inputs=["source latent", "optional donor latent", "DSP mode", "strength"],
        outputs=["latent artifact", "recipe", "operator metadata"],
    ),
    NotebookMode(
        mode_id="0f",
        title="Cyclic time-roll loop lab",
        priority="P1",
        maturity="lab",
        status="partial app surface",
        native_surface="Latent Lab cyclic roll plus MLX inpaint; iterative loop repair is queued",
        operators=[OperatorName.LATENT_CYCLIC_ROLL, OperatorName.INPAINT],
        inputs=["source audio or latent", "shift_frames", "inpaint range", "steps"],
        outputs=["audio or latent artifact", "recipe"],
    ),
    NotebookMode(
        mode_id="0g",
        title="Cyclic roll inside denoising trajectory",
        priority="P2",
        maturity="probe",
        status="scaffold",
        native_surface="Sampler-level surgery queued; cyclic latent roll is available as a proxy",
        operators=[OperatorName.LATENT_CYCLIC_ROLL],
        inputs=["source latent", "roll fraction", "per-step mix"],
        outputs=["planned sampler trace", "audio artifact"],
        notes="The notebook version requires intervening inside the SA3 sampling loop.",
    ),
    NotebookMode(
        mode_id="flow-sign",
        title="Flow sign diagnostic",
        priority="P2",
        maturity="probe",
        status="scaffold",
        native_surface="Diagnostic recipe queued",
        inputs=["target audio", "candidate prompts", "velocity convention"],
        outputs=["loss comparison JSON"],
    ),
    NotebookMode(
        mode_id="1",
        title="Audio to soft prompt",
        priority="P1",
        maturity="probe",
        status="native recipe",
        native_surface="Recipe Studio: optimize soft prompt",
        operators=[OperatorName.EXPERIMENT_SOFT_PROMPT_OPTIMIZE],
        scripts=["scripts/optimize_sa3_soft_prompt.py"],
        inputs=["target audio path or selected audio artifact", "seed prompt", "optimization parameters"],
        outputs=["soft_prompt.pt bundle", "recipe", "loss logs"],
    ),
    NotebookMode(
        mode_id="1b",
        title="Generate with a soft prompt",
        priority="P1",
        maturity="lab",
        status="native recipe",
        native_surface="Recipe Studio: generate soft prompt",
        operators=[OperatorName.EXPERIMENT_SOFT_PROMPT_GENERATE],
        scripts=["scripts/generate_sa3_with_soft_prompt.py"],
        inputs=["soft prompt .pt", "seed", "steps", "cfg"],
        outputs=["audio artifact", "recipe"],
    ),
    NotebookMode(
        mode_id="2",
        title="Audio to babble / hard prompt",
        priority="P2",
        maturity="probe",
        status="scaffold",
        native_surface="Prompt-search recipe queued",
        inputs=["target audio", "token vocabulary", "beam/greedy budget"],
        outputs=["prompt JSON", "score history"],
        notes="Core prompt search helpers exist in latent_audio_primitives.prompt_optimization.",
    ),
    NotebookMode(
        mode_id="3",
        title="Audio to readable prompt",
        priority="P2",
        maturity="probe",
        status="scaffold",
        native_surface="Readable prompt-search recipe queued",
        inputs=["target audio", "modifier axes", "search rounds"],
        outputs=["prompt JSON", "score history"],
    ),
    NotebookMode(
        mode_id="4",
        title="Dataset to soft prompt",
        priority="P2",
        maturity="probe",
        status="partial recipe",
        native_surface="Recipe Studio can pre-encode datasets and optimize a target soft prompt; batch dataset optimizer is queued",
        operators=[OperatorName.DATASET_PRE_ENCODE, OperatorName.EXPERIMENT_SOFT_PROMPT_OPTIMIZE],
        scripts=["scripts/pre_encode_dataset.py", "scripts/optimize_sa3_soft_prompt.py"],
        inputs=["audio folder", "duration/chunk settings", "optimization parameters"],
        outputs=["encoded dataset bundle", "soft_prompt.pt"],
    ),
    NotebookMode(
        mode_id="5",
        title="Dataset to prompt family",
        priority="P2",
        maturity="probe",
        status="scaffold",
        native_surface="Clustered memory/prompt-family recipe queued",
        inputs=["encoded memory", "cluster count", "soft prompt parameters"],
        outputs=["cluster manifests", "soft prompts"],
    ),
    NotebookMode(
        mode_id="6",
        title="SAME latent style profile",
        priority="P1",
        maturity="lab",
        status="native recipe",
        native_surface="Recipe Studio: positive style profile, build profile, generate from profile",
        operators=[
            OperatorName.EXPERIMENT_POSITIVE_STYLE_PROFILE,
            OperatorName.EXPERIMENT_STYLE_PROFILE_BUILD,
            OperatorName.EXPERIMENT_STYLE_PROFILE_GENERATE,
        ],
        scripts=[
            "scripts/build_positive_audio_style_profile.py",
            "scripts/build_same_style_profile.py",
            "scripts/generate_sa3_with_style_profile.py",
        ],
        inputs=["audio folder or memory folder", "profile path", "prompt", "alpha"],
        outputs=["profile bundle", "audio artifact"],
    ),
    NotebookMode(
        mode_id="7",
        title="SAME latent direction",
        priority="P1",
        maturity="lab",
        status="native recipe",
        native_surface="Recipe Studio: audio style vectors, build direction, generate from direction",
        operators=[
            OperatorName.EXPERIMENT_AUDIO_STYLE_VECTORS,
            OperatorName.EXPERIMENT_STYLE_PROFILE_BUILD,
            OperatorName.EXPERIMENT_STYLE_DIRECTION_GENERATE,
            OperatorName.EXPERIMENT_AUDIO_DIRECTION_GENERATE,
        ],
        scripts=[
            "scripts/extract_audio_style_vectors.py",
            "scripts/build_same_style_profile.py",
            "scripts/generate_sa3_with_style_direction.py",
            "scripts/generate_sa3_with_audio_direction.py",
        ],
        inputs=["positive/reference folders", "direction path", "prompt", "alpha"],
        outputs=["direction bundle", "audio artifact"],
    ),
    NotebookMode(
        mode_id="8",
        title="SA3 residual steering from prompts",
        priority="P1",
        maturity="probe",
        status="native recipe",
        native_surface="Recipe Studio: prompt residual vectors and alpha sweep",
        operators=[OperatorName.EXPERIMENT_SA3_VECTORS_EXTRACT, OperatorName.EXPERIMENT_ALPHA_SWEEP],
        scripts=["scripts/extract_sa3_vectors.py", "scripts/run_sa3_alpha_sweep.py"],
        inputs=["axis", "prompt pairs", "layers", "alphas"],
        outputs=["vector bundle", "alpha sweep audio family"],
    ),
    NotebookMode(
        mode_id="9",
        title="SA3 residual steering from audio",
        priority="P1",
        maturity="probe",
        status="native recipe",
        native_surface="Recipe Studio: audio residual vectors and alpha sweep",
        operators=[OperatorName.EXPERIMENT_AUDIO_RESIDUAL_VECTORS_EXTRACT, OperatorName.EXPERIMENT_ALPHA_SWEEP],
        scripts=["scripts/extract_audio_residual_vectors.py", "scripts/run_sa3_alpha_sweep.py"],
        inputs=["positive/negative audio folders", "baseline", "layers", "alphas"],
        outputs=["vector bundle", "alpha sweep audio family"],
    ),
    NotebookMode(
        mode_id="10",
        title="Noise / trajectory optimization scaffold",
        priority="P3",
        maturity="probe",
        status="scaffold",
        native_surface="Flow-state optimizer recipe queued",
        inputs=["target audio", "prompt", "timestep", "learning rate"],
        outputs=["loss curve", "optimized flow state"],
    ),
    NotebookMode(
        mode_id="11",
        title="Inpainting / continuation as composition",
        priority="P1",
        maturity="core",
        status="native app surface",
        native_surface="Listening Bench inpaint/audio-to-audio generation",
        operators=[OperatorName.INPAINT, OperatorName.AUDIO_TO_AUDIO],
        inputs=["source audio", "prompt", "range", "duration", "seed"],
        outputs=["audio artifact", "recipe", "lineage"],
    ),
    NotebookMode(
        mode_id="12",
        title="LatCH-style control heads",
        priority="P3",
        maturity="probe",
        status="scaffold",
        native_surface="Control-head training recipe queued",
        inputs=["latent memory", "descriptor labels", "control name"],
        outputs=["control_head.pt", "training metrics"],
    ),
    NotebookMode(
        mode_id="14",
        title="Latent memory instrument",
        priority="P2",
        maturity="lab",
        status="native app surface",
        native_surface="Artifact store, latent import/encode, lineage, dataset pre-encode, and memory query recipe",
        operators=[OperatorName.LATENT_ENCODE, OperatorName.DATASET_PRE_ENCODE, OperatorName.MEMORY_QUERY],
        scripts=["scripts/pre_encode_dataset.py", "scripts/encode_dataset_same.py"],
        inputs=["audio artifacts", "latent artifacts", "memory folders"],
        outputs=["latent artifacts", "encoded memory bundle", "retrieval results"],
    ),
    NotebookMode(
        mode_id="15",
        title="SAME geometry and intervention audit",
        priority="P2",
        maturity="probe",
        status="partial native recipe",
        native_surface="Recipe Studio: geometry audit over local latent artifacts; intervention/control probes are queued",
        operators=[OperatorName.EXPERIMENT_GEOMETRY_AUDIT],
        inputs=["selected latent or session latents", "component count", "limit"],
        outputs=["geometry report JSON bundle", "variance and summary metrics"],
        notes="This promotes the saved-latent geometry audit. Periodicity and control-head probes still need labelled descriptors.",
    ),
    NotebookMode(
        mode_id="combined",
        title="Audio-derived prompt + residual knob + SAME style push",
        priority="P3",
        maturity="lab",
        status="chainable by recipes",
        native_surface="Run Recipe Studio modes sequentially; chain macro UI is queued",
        operators=[
            OperatorName.EXPERIMENT_SOFT_PROMPT_OPTIMIZE,
            OperatorName.EXPERIMENT_SOFT_PROMPT_GENERATE,
            OperatorName.EXPERIMENT_ALPHA_SWEEP,
            OperatorName.EXPERIMENT_STYLE_PROFILE_GENERATE,
        ],
        inputs=["target audio", "soft prompt", "residual vectors", "style profile"],
        outputs=["combined audio artifact", "memory item"],
    ),
)


def list_colab_modes() -> list[NotebookMode]:
    return list(COLAB_MODES)
